# Generated by Django 5.0.2 on 2024-06-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_hiden',
            field=models.BooleanField(default=False),
        ),
    ]
