# Generated by Django 5.0.2 on 2024-06-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_customuser_is_hiden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_hiden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
