# Generated by Django 5.0.2 on 2024-06-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_desk'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='lokasi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
